<?php
require 'vendor/autoload.php';
$app = require_once 'bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();

use App\Models\Subject;

// Fix all bad codes generated by previous fallback method
$fixes = [
    // School 1 (SMPS)
    4 => 'IPA',     // Ilmu Pengetahuan Alam
    5 => 'IPS',     // Ilmu Pengetahuan Sosial
    6 => 'PKN',     // Pendidikan Kewarganegaraan
    7 => 'PJOK',    // Pendidikan Jasmani
    141 => 'PA-KAT', // Pend. Agama Katolik
    142 => 'PAK',    // Pend. Agama Kristen
    144 => 'BK',     // Bimbingan Konseling
    146 => 'PRKR',   // Prakarya
    227 => 'BDAE',   // Bahasa Daerah
    228 => 'PAI',    // Pend. Agama Islam
    
    // School 2 (SMAS)
    19 => 'PJOK',    // Pendidikan Jasmani
];

echo "Fixing bad subject codes...\n";
$count = 0;
foreach ($fixes as $id => $code) {
    $s = Subject::find($id);
    if ($s) {
        $old = $s->code;
        $s->code = $code;
        $s->save();
        echo "  Fixed ID $id: '{$s->name}' => '$old' -> '$code'\n";
        $count++;
    }
}

echo "\nFixed $count subjects.\n";
